config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root                 'static_pages#home'
  get  '/home',    to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    def hello
      render html: "hello, world!"
    end
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @image_array = ['image1.jpg', 'image2.jpg', 'image3.jpg',
                    'image4.jpg', 'image5.jpg']
    @rand_result = (0..4).to_a.shuffle.first
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
   end

   def new
   end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SOL", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Student Organization of Latinx (SOL)</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  <br>
  This is the sample application for the tutorial.
  This site showcases my skill development with rails because before this class
  I would not have been able to make a home page. This website showcases how
  I've learned to utilize MVC model to create static pages. How I can use CSS
  to style the webpage. How I've added a database, and how I've been able to add
  images to the page. It shows, I've actually developed skills with ruby  and rails.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis eu sapien vel pretium. Nunc non odio cursus, faucibus enim id, cursus eros. Maecenas cursus orci non neque luctus faucibus. Morbi ac suscipit est. Proin eget vehicula augue, ac egestas orci. Fusce suscipit sapien sit amet placerat fringilla. Aenean sollicitudin diam sit amet felis lacinia lobortis. Nam tristique consectetur sem. Pellentesque nec dolor vel tortor congue rhoncus eget sed mauris. Aliquam diam elit, pretium non dapibus sed, feugiat et risus. Morbi congue neque libero, eget porta turpis tincidunt vel. Etiam auctor placerat elit in mollis. Aliquam vel accumsan dolor. Nullam tincidunt mauris tortor. Sed tincidunt sollicitudin ultrices. Nunc at neque sed urna vulputate mattis.
  <br/>
  Donec non efficitur turpis, sit amet pulvinar nunc. Fusce dictum efficitur enim, congue porttitor sem interdum quis. Nulla et massa sed libero consectetur pharetra sed et libero. Curabitur porttitor turpis at vestibulum sagittis. Donec cursus augue eu augue bibendum pulvinar. Vivamus eu risus urna. Aenean ultricies magna a suscipit iaculis.
  <br/>
  Donec eu nisl ut justo faucibus sollicitudin a ut turpis. Ut et sagittis arcu. Praesent ligula enim, interdum nec semper at, consequat eu felis. Nunc at mattis metus. Duis sit amet tincidunt neque, quis molestie nunc. Integer sed vulputate turpis, et sollicitudin leo. Etiam vehicula dui pulvinar risus ullamcorper pretium. Vestibulum ac consectetur risus. Cras eu lectus et urna ultricies accumsan ac sed felis. Quisque consectetur quis diam vel accumsan. Integer commodo hendrerit tristique.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis eu sapien vel pretium. Nunc non odio cursus, faucibus enim id, cursus eros. Maecenas cursus orci non neque luctus faucibus. Morbi ac suscipit est. Proin eget vehicula augue, ac egestas orci. Fusce suscipit sapien sit amet placerat fringilla. Aenean sollicitudin diam sit amet felis lacinia lobortis. Nam tristique consectetur sem. Pellentesque nec dolor vel tortor congue rhoncus eget sed mauris. Aliquam diam elit, pretium non dapibus sed, feugiat et risus. Morbi congue neque libero, eget porta turpis tincidunt vel. Etiam auctor placerat elit in mollis. Aliquam vel accumsan dolor. Nullam tincidunt mauris tortor. Sed tincidunt sollicitudin ultrices. Nunc at neque sed urna vulputate mattis.
  <br>
  Donec non efficitur turpis, sit amet pulvinar nunc. Fusce dictum efficitur enim, congue porttitor sem interdum quis. Nulla et massa sed libero consectetur pharetra sed et libero. Curabitur porttitor turpis at vestibulum sagittis. Donec cursus augue eu augue bibendum pulvinar. Vivamus eu risus urna. Aenean ultricies magna a suscipit iaculis.
  <br>
  Donec eu nisl ut justo faucibus sollicitudin a ut turpis. Ut et sagittis arcu. Praesent ligula enim, interdum nec semper at, consequat eu felis. Nunc at mattis metus. Duis sit amet tincidunt neque, quis molestie nunc. Integer sed vulputate turpis, et sollicitudin leo. Etiam vehicula dui pulvinar risus ullamcorper pretium. Vestibulum ac consectetur risus. Cras eu lectus et urna ultricies accumsan ac sed felis. Quisque consectetur quis diam vel accumsan. Integer commodo hendrerit tristique.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>SOL Website</h1>
<h2>
    <%= link_to image_tag(@image_array[@rand_result], width: '400') %> <br/>
    <%= link_to "New Random Image", '/home'%> <br/>
    This is the home page for the
    SOL student group, on campus.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mattis eu sapien vel pretium. Nunc non odio cursus, faucibus enim id, cursus eros. Maecenas cursus orci non neque luctus faucibus. Morbi ac suscipit est. Proin eget vehicula augue, ac egestas orci. Fusce suscipit sapien sit amet placerat fringilla. Aenean sollicitudin diam sit amet felis lacinia lobortis. Nam tristique consectetur sem. Pellentesque nec dolor vel tortor congue rhoncus eget sed mauris. Aliquam diam elit, pretium non dapibus sed, feugiat et risus. Morbi congue neque libero, eget porta turpis tincidunt vel. Etiam auctor placerat elit in mollis. Aliquam vel accumsan dolor. Nullam tincidunt mauris tortor. Sed tincidunt sollicitudin ultrices. Nunc at neque sed urna vulputate mattis.
    <br>
    Donec non efficitur turpis, sit amet pulvinar nunc. Fusce dictum efficitur enim, congue porttitor sem interdum quis. Nulla et massa sed libero consectetur pharetra sed et libero. Curabitur porttitor turpis at vestibulum sagittis. Donec cursus augue eu augue bibendum pulvinar. Vivamus eu risus urna. Aenean ultricies magna a suscipit iaculis.
    <br>
    Donec eu nisl ut justo faucibus sollicitudin a ut turpis. Ut et sagittis arcu. Praesent ligula enim, interdum nec semper at, consequat eu felis. Nunc at mattis metus. Duis sit amet tincidunt neque, quis molestie nunc. Integer sed vulputate turpis, et sollicitudin leo. Etiam vehicula dui pulvinar risus ullamcorper pretium. Vestibulum ac consectetur risus. Cras eu lectus et urna ultricies accumsan ac sed felis. Quisque consectetur quis diam vel accumsan. Integer commodo hendrerit tristique.
  </h2>

app/views/users/email:string.html.erb
<h1>Users#email:string</h1>
<p>Find me in app/views/users/email:string.html.erb</p>

app/views/users/name:string.html.erb
<h1>Users#name:string</h1>
<p>Find me in app/views/users/name:string.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>